### ISSUE TITLE
edge driver fails to open session on windows 10

### ISSUE THREAD

**Issue by adrian-herscu** [QA-Automation-Starter/qa-automation#193]
**Description**
Edge driver fails to open local session on Windows 10.

**Reproduction**

1. run TestingWebApplication with EdgeDriver

**Expected behavior**
Tests should pass, at least partially.

**Additional context**
Maybe blocked via IT's group policy (?)

**Comment by adrian-herscu** [comment]
```
12:10:33.432 [TRACE] [main ] [1]: TestingWebApplication - setting up edge driver
Exception occured while running tests.
org.testng.TestNGException: 
The factory method class com.acme.testing.scenarios.attic.TestingWebApplication.com.acme.testing.scenarios.attic.TestingWebApplication() threw an exception
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:223)
	at org.testng.internal.TestNGClassFinder.processFactory(TestNGClassFinder.java:174)
	at org.testng.internal.TestNGClassFinder.processMethod(TestNGClassFinder.java:138)
	at org.testng.internal.TestNGClassFinder.processClass(TestNGClassFinder.java:129)
	at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:67)
	at org.testng.TestRunner.initMethods(TestRunner.java:461)
	at org.testng.TestRunner.init(TestRunner.java:356)
	at org.testng.TestRunner.init(TestRunner.java:309)
	at org.testng.TestRunner.<init>(TestRunner.java:184)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:652)
	at org.testng.SuiteRunner.init(SuiteRunner.java:224)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:116)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1375)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1349)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1191)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.microsoft.java.test.runner.testng.TestNGRunner.run(TestNGRunner.java:45)
	at com.microsoft.java.test.runner.testng.TestNGLauncher.execute(TestNGLauncher.java:32)
	at com.microsoft.java.test.runner.Launcher.main(Launcher.java:57)
Caused by: org.testng.TestNGException: 
Cannot instantiate class com.acme.testing.scenarios.attic.TestingWebApplication
	at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:41)
	at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:18)
	at org.testng.internal.FactoryMethod.invoke(FactoryMethod.java:211)
	... 19 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

```
